# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20170409_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemtousermessage',
            options={'verbose_name': '系统消息', 'verbose_name_plural': '系统消息'},
        ),
    ]
