# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20170410_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
