# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_usertousermessage_send_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertousermessage',
            old_name='send_place',
            new_name='is_send',
        ),
    ]
