# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0004_usermessagestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessagestatus',
            name='even_message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermessagestatus',
            name='system_to_user_message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermessagestatus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessagestatus',
            name='user_to_user_message_count',
            field=models.IntegerField(default=0),
        ),
    ]
