# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20170416_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmessage',
            options={'verbose_name': '事件消息', 'verbose_name_plural': '事件消息'},
        ),
        migrations.AlterModelOptions(
            name='usermessagestatus',
            options={'verbose_name': '用户信息状态', 'verbose_name_plural': '用户信息状态'},
        ),
        migrations.AlterModelOptions(
            name='usertousermessage',
            options={'verbose_name': '用户消息', 'verbose_name_plural': '用户消息'},
        ),
    ]
