# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20170416_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtousermessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
