# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_eventmessage_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmessage',
            old_name='tittle',
            new_name='brief_content',
        ),
        migrations.RemoveField(
            model_name='eventmessage',
            name='content',
        ),
    ]
