# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20170419_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmessage',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
