# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20170416_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemtousermessage',
            name='tittle',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemtousermessage',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
