# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20170419_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmessage',
            name='event_type',
            field=models.CharField(choices=[('being_liked', '收到赞'), ('being_answering', '收到答案'), ('being_at', '收到@')], max_length=20),
        ),
    ]
