# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20170418_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': '朋友', 'verbose_name_plural': '朋友'},
        ),
        migrations.AlterField(
            model_name='systemtousermessage',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
