# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 05:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0010_auto_20170418_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertousermessage',
            options={'verbose_name': '私信', 'verbose_name_plural': '私信'},
        ),
        migrations.AddField(
            model_name='usertousermessage',
            name='content',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertousermessage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertousermessage',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='B_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertousermessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='A_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
