# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_usertousermessagesession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertousermessagesession',
            options={'verbose_name': '用户会话', 'verbose_name_plural': '用户会话'},
        ),
    ]
