# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_auto_20170421_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertousermessage',
            name='is_send',
        ),
    ]
