# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0012_auto_20170418_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMessageStatus',
            new_name='MessageStatus',
        ),
    ]
