# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0013_auto_20170418_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestatus',
            name='all_count',
            field=models.IntegerField(default=0),
        ),
    ]
