# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_messagestatus_all_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagestatus',
            name='all_count',
        ),
    ]
