# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '时间轴', 'verbose_name_plural': '时间轴'},
        ),
    ]
