# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20170408_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tittle',
        ),
    ]
