# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_remove_comment_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=600),
        ),
    ]
