# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionModel',
            new_name='Collection',
        ),
    ]
