# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': '父帖子类型', 'verbose_name_plural': '父帖子类型'},
        ),
        migrations.AlterModelOptions(
            name='subclass',
            options={'verbose_name': '子帖子类型', 'verbose_name_plural': '子帖子类型'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='chinese_name',
        ),
        migrations.RemoveField(
            model_name='subclass',
            name='chinese_name',
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名字'),
        ),
    ]
