# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170408_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='sub_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.SubClass'),
        ),
    ]
