# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170228_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subclass',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='subclass',
            name='pclass',
        ),
        migrations.DeleteModel(
            name='SubClass',
        ),
    ]
