# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20170409_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='display_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='显示名字'),
        ),
        migrations.AddField(
            model_name='subclass',
            name='display_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='显示名字'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='name'),
        ),
    ]
