# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170409_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subclass',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
