# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170303_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='chinese_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
