# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20170410_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='显示名字'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='display_name',
            field=models.CharField(max_length=50, verbose_name='显示名字'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名字'),
        ),
    ]
