# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20170411_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subclass',
            options={'ordering': ['parent_class', 'order'], 'verbose_name': '子帖子类型', 'verbose_name_plural': '子帖子类型'},
        ),
    ]
