# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20170411_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='main_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Class'),
        ),
    ]
