# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_thread_main_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSummer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
