# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_usersummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclass',
            name='parent_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Class'),
        ),
    ]
