# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20170411_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclass',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='thread',
            name='sub_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.SubClass'),
        ),
    ]
