# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20170411_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='tittle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
