# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_auto_20170411_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
