# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 05:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20170413_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
