# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20170413_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='tittle',
            field=models.CharField(max_length=100),
        ),
    ]
