# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_auto_20170413_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='thread',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='forum.Thread'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='click',
            field=models.IntegerField(default=0),
        ),
    ]
