# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_auto_20170414_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='reply',
            field=models.IntegerField(default=0),
        ),
    ]
