# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_auto_20170414_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=' s'),
            preserve_default=False,
        ),
    ]
