# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0032_auto_20170416_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userthreadstatus',
            options={'verbose_name': '用户状态', 'verbose_name_plural': '用户状态'},
        ),
    ]
