# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0033_auto_20170419_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='score',
            field=models.IntegerField(default=1000),
        ),
    ]
