# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashpoint',
            options={'verbose_name': '现金积分', 'verbose_name_plural': '现金积分'},
        ),
    ]
