# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_creditexchangecode_onlinelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditexchangecode',
            options={'verbose_name': '积分兑换', 'verbose_name_plural': '积分兑换'},
        ),
        migrations.AlterField(
            model_name='creditdefault',
            name='credit_point',
            field=models.IntegerField(default=0),
        ),
    ]
