# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 03:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit', '0007_auto_20170420_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('brief_content', models.CharField(max_length=50)),
                ('credit_change', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
            },
        ),
        migrations.AlterModelOptions(
            name='creditdefault',
            options={'verbose_name': '用户积分状态', 'verbose_name_plural': '用户积分状态'},
        ),
    ]
