# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0012_creditlog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlog',
            name='brief_content',
            field=models.TextField(),
        ),
    ]
