# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0013_auto_20170420_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditexchangecode',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
