# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0014_creditexchangecode_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditexchangecode',
            old_name='date',
            new_name='time',
        ),
    ]
