# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0015_auto_20170420_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinelog',
            options={'verbose_name': '在线记录', 'verbose_name_plural': '在线记录'},
        ),
        migrations.RenameField(
            model_name='onlinelog',
            old_name='date',
            new_name='time',
        ),
    ]
