# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0016_auto_20170420_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='everydaysign',
            old_name='date',
            new_name='time',
        ),
    ]
