# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0017_auto_20170420_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='everydaysign',
            options={'verbose_name': '每日签到', 'verbose_name_plural': '每日签到'},
        ),
    ]
