# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': '历史', 'verbose_name_plural': '历史'},
        ),
    ]
