# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
