# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_history_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='brief_content',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
