# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20170418_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
