# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20170418_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='type',
            field=models.CharField(choices=[('asking', '你的提问'), ('answering', 'answering'), ('liking', 'liking'), ('collecting', 'collecting')], max_length=20),
        ),
    ]
