# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_auto_20170418_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='type',
            field=models.CharField(choices=[('asking', '提问'), ('answering', '回答'), ('liking', '点赞'), ('collecting', '收藏')], max_length=20),
        ),
    ]
