# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_auto_20170419_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='brief_content',
            field=models.TextField(),
        ),
    ]
