# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20170227_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True)),
                ('tittle', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
    ]
