# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_postmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
