# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systememailinfo',
            options={'verbose_name': '系统邮箱', 'verbose_name_plural': '系统邮箱'},
        ),
    ]
