# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20170416_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeSystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=80)),
                ('content', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
