# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_path',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
