# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_path',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
