# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20170228_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_path',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='cat/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
