# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20170228_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_place',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
