# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_userprofile_work_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lang',
            new_name='language',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_nickname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
