# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20170228_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sign',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
    ]
