# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_userprofile_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sign',
            new_name='self_introduction',
        ),
    ]
