# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20170301_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='set_avatar',
            field=models.BooleanField(default=False),
        ),
    ]
