# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_userprofile_set_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_year',
            field=models.IntegerField(default=0),
        ),
    ]
