# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_userprofile_blog_adderss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default=index.models.default_avatar, null=True, upload_to=index.models.upload_to),
        ),
    ]
