# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20170304_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='work_nickname',
            field=models.CharField(max_length=20, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_place',
            field=models.CharField(max_length=20, verbose_name='工作单位'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_year',
            field=models.IntegerField(default=0, verbose_name='工作年限'),
        ),
    ]
