# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20170409_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='使用语言'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='self_introduction',
            field=models.CharField(max_length=300, verbose_name='自我介绍'),
        ),
    ]
