# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20170412_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blog_adderss',
            field=models.URLField(blank=True),
        ),
    ]
