# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_remove_userprofile_set_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=index.models.default_avatar, upload_to=index.models.upload_to),
        ),
    ]
