# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20170418_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='blog_adderss',
            new_name='blog_address',
        ),
    ]
